---
# roles/idrac/local/tasks/main.yml

- name: Create local samba dir
  file: path={{local_samba_path}} state=directory

- name: Create firmware dir
  file: path={{local_firmware_path}} state=directory

- name: Copy XML file to /var/samba
  copy: src=files/idrac_xml/ dest=/var/samba/ directory_mode=yes mode=644
        #owner=ansible group=ansible mode=644

- name: Download firmware from Dell
  get_url: url={{ item.value.url }}
    dest={{local_firmware_path}}/{{ item.value.url | basename }}
  with_recursive:
   - { name: dict, args: firmware }
   - { name: dict, args: "{{item.value}}" }

- name: Install WSMAN
  yum: name=wsmancli state=present

# TODO install dell-wsman-client-api-python from 
# github.com/hbeatty/dell-wsman-client-api-python.git
