---
# file: roles/idrac/firmware/tasks/biosInstall.yml

- name: Install BIOS
  local_action:
    module: idrac
    username: "{{ lom_user }}"
    password: "{{ lom_pass }}"
    hostname: "{{ lom_hostname }}"
    name: "InstallBIOS"
    firmware:
      "{{firmware[SystemGeneration].bios}}"
