---
# file: roles/idrac/firmware/tasks/debug.yml

- debug: var=Model

- debug: var=SystemGeneration

- debug: var=LifecycleControllerVersion

- debug: var=firmware[SystemGeneration]['idrac']['target_version']

# This pulls the idrac firmware but, has all models
- debug: msg={{ item.key }}
  when: item.key == 'idrac'
  with_recursive:
   - { name: dict, args: firmware }
   - { name: dict, args: "{{item.value}}" }

# Limit to just the idrac
- debug: var=item
  when: item.key == 'idrac'
  with_dict: firmware[SystemGeneration]

# Limit to a single SystemGeneration
- debug: msg={{ item.value }}
  when: SystemGeneration == item.key
  with_recursive:
    - { name: dict, args: firmware }

# All firmware limited to a single SystemGeneration
- debug: msg={{ item.key }}
  with_dict: firmware[SystemGeneration]

