---
# file: provisioning/roles/idrac-firmware/tasks/firmware.yml

- name: Delete the Job Queue
  local_action: idrac username={{lom_user}} password={{lom_pass}}
    hostname={{ lom_hostname }} command="DeleteJobQueue"

- name: Upgrade NIC
  local_action: idrac username={{ lom_user }} password={{ lom_pass }}
    hostname={{ lom_hostname }} command="UpgradePerc"
    share_pass={{ share_pass }} share_user={{ share_user }}
    share_ip={{ share_ip }} share_name={{ share_name }}
    share_type={{ share_type }} firmware={{ R730xd.gigNicInstanceID1 }}
    instanceID={{ R730xd.gigNicInstanceID1}}
  register: result
  when: Model.find('730xd') != -1

