---
# file: roles/idrac/firmware/tasks/firmwareInstall.yml

- name: Install Firmware
  local_action:
    module: idrac
    username: "{{ lom_user }}"
    password: "{{ lom_pass }}"
    hostname: "{{ lom_hostname }}"
    command: "InstallFirmware"
    firmware: 
      "{{ firmware[SystemGeneration] }}"
  register: result

# Give a pretty output of how the install went
- debug: var=result.result
