---
# file : roles/idrac/firmware/tasks/idracFirmwareInstall.yml

# TODO add a log message
#- name: Life Cycle Log message for iDrac Firmware Upgrade Start
#  local_action: racadm username={{ lom_user }} password={{ lom_pass }} host={{ lom_hostname }} cmd="lclog worknote add -m \"Starting iDrac Firmware upgrade\""

#- debug: var=firmware[Model].idrac

- name: Install iDRAC firmware
  local_action:
    module: idrac
    username: "{{lom_user}}"
    password: "{{lom_pass}}"
    hostname: "{{lom_hostname}}"
    command: "InstallIdracFirmware"
    debug: "True"
    firmware:
      "{{firmware[Model].idrac}}"

- name: Check iDRAC status after upgrade
  local_action: idrac username={{lom_user}} password={{lom_pass}}
                hostname={{lom_hostname}} command="CheckReadyState"
  

