---
# file : provisioning/roles/idrac-firmware/tasks/idrac.yml

- name: Life Cycle Log message for iDrac Firmware Upgrade Start
  local_action: racadm username={{ lom_user }} password={{ lom_pass }} host={{ lom_hostname }} cmd="lclog worknote add -m \"Starting iDrac Firmware upgrade\""

# The below is no longer necessary because the InstallIdracFirmware checks
# the job queue and aborts if there are pending jobs.
#- name: Delete the Job Queue
#  local_action: idrac username={{lom_user}} password={{lom_pass}}
#    hostname={{lom_hostname}} command="DeleteJobQueue"

#- debug: var=firmware[Model].idrac

# TODO figure out a way to not have so many variables. Spcifically git rid of
# the username and password to connect to the iDRAC.
- name: Install iDRAC firmware
  local_action:
    module: idrac
    username: "{{lom_user}}"
    password: "{{lom_pass}}"
    hostname: "{{lom_hostname}}"
    command: "InstallIdracFirmware"
    debug: "True"
    firmware_info:
      "{{firmware[Model].idrac}}"

- name: Check iDRAC status after upgrade
  local_action: idrac username={{lom_user}} password={{lom_pass}}
                hostname={{lom_hostname}} command="CheckReadyState"
  

