---
# file: roles/idrac/firmware/tasks/main.yml

- name: Make sure iDrac is ready
  local_action: idrac username={{lom_user}} password={{lom_pass}}
                hostname={{lom_hostname}} command="CheckReadyState"

#- include: debug.yml
  
# This one has to be run seperately because it causes an automatic reset of the 
# iDRAC
- include: idracFirmwareInstall.yml

# Run seperately because it reboots the server
- include: biosInstall.yml

# Install the other firmware
- include: firmwareUpgrade.yml
